### ISSUE TITLE
Background is tiled

### ISSUE THREAD

**Issue by luciandean2004** [LouieK22/louiek22.github.io#1]
Background is tiled. It should be stretched to fit screen. Requires CSS file.

**Comment by LouieK22** [comment]
Please fix, also I'm testing sending this from my email.

On Wed, Jul 13, 2016, 10:05 PM luciandean2004 <notifications@github.com>
wrote:

> Background is tiled. It should be stretched to fit screen. Requires CSS
> file.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/LouieK22/louiek22.github.io/issues/1>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AKRDyiQp91j5aF6EaYjm0PaJ-j6ob62wks5qVadmgaJpZM4JMCpV>
> .
>
-- 
-Martin, Resident Techie

**Comment by LouieK22** [comment]
Looks like responding to this via email formats weirdly. Oh well, plz fix thx
